Lesson 7
tanianova/geekshop pull request #7
Opened 2021-02-10 13:11 UTC by tanianova

2021-02-10 19:04 UTC, Vokler requested changes

2021-02-10 19:04 UTC, Vokler commented on adminapp/forms.py
> +    price = forms.DecimalField(max_digits=8, decimal_places=2)
В целом необязательно перечислять здесь все переменные. Их нужно объявить, например, для image, потому что требуется дополнительный атрибут, такой как `widget=forms.FileInput`. Остальные переменные, в которых нет никаких дополнительных изменений, такие как full_description, short_description, price и тд, можно убрать. Все подгрузится из БД

А вот в fields обязательно оставить, так как там перечисление обязательно

2021-02-10 19:04 UTC, Vokler commented on adminapp/forms.py
> +        super(ProductAdminUpdateForm, self).__init__(*args, **kwargs)
У вас init никак не дополняется/переопределяется, поэтому смело можно убрать

2021-02-11 08:04 UTC, tanianova commented on adminapp/forms.py
> +    price = forms.DecimalField(max_digits=8, decimal_places=2)
Спасибо, поправила)

2021-02-11 16:32 UTC, Vokler approved these changes

2021-02-11 16:32 UTC, merged